### ISSUE TITLE
What? No support for special characters in file names?

### ISSUE THREAD

**Issue by Fresheyeball** [ltext/ltext#1]
Look, you can't just ignore the possibility. Who doesn't want files with unicode smilies as the end? WHO!

**Comment by athanclark** [comment]
So the only strings I _can't_ allow (yet) are:
- `->` (continuous and space-separated. `-` and `>` are fine alone)
- `\` (...we don't need windows users.)

The second one is going to be tricky to fix, but I think it's fine if windows users use absolute paths or relative paths (because they don't have UNIX-style `/`-as-root, anyway) for their term names. Also, you **can** have `->.txt` as a file.
